os: Visual Studio 2019

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: fcs\build.cmd NuGet

test: off
version: '{build}'
artifacts:
  - path: artifacts\bin\fcs\Release\*.nupkg
  - path: artifacts\packages\Release\Shipping\*.nupkg